export const leaning_df3 = [
    {
        "no": "0",
        "title": "Question about us gamers",
        "score": "2",
        "id": "i5a7p5",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i5a7p5/question_about_us_gamers/",
        "num_comments": "18",
        "body": "Does the power consumption we have on our builds affect this?\n\nor are we all just a drop of water in a big bucket.\n\ni mean i see some pc builds whose power consumption goes up to almost if not a KW \n\nshould companies be blocked i  releasing videocards that consume.more than 150wats? \nor cpu with no more than 65?",
        "created": "2020-08-07",
        "comment": "I remember seeing a nice graph showing the annual power consumption of gaming in America compared to transport and other things, can't find it right now, but I did manage to find this article which sums it up pretty clearly: \n\n [https://www.pcgamesn.com/microsoft/gaming-environmental-impact](https://www.pcgamesn.com/microsoft/gaming-environmental-impact) \n\n\" **Counting PCs, laptops, and consoles, gaming hardware has the same carbon footprint as 85 million refrigerators or 5 million gas-guzzling cars.** \" - not worldwide, but in America.\n\nThe article also makes some points about companies intending to significantly reduce their footprint by making hardware more efficient (playstation 5 promises greener efficiency and Logitech also promised to go greener I've read somewhere today, in the sense of being carbon neutral in their production or something to that effect).\n\nHowever as usual I really see the onus being primarily on the governments and economy - individuals like us can in little to no way really effect how companies manufacture their goods, or source their power, or design their hardware. Sure, we can take ourselves out of the equation or reduce our individual impact, but I don't see how that's a realistic solution, albeit being maybe a sensible and decent thing to do.",
        "is_same_stance": "F",
        "author_leaning": "R"
    },
    {
        "no": "1",
        "title": "Question about us gamers",
        "score": "2",
        "id": "i5a7p5",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i5a7p5/question_about_us_gamers/",
        "num_comments": "18",
        "body": "Does the power consumption we have on our builds affect this?\n\nor are we all just a drop of water in a big bucket.\n\ni mean i see some pc builds whose power consumption goes up to almost if not a KW \n\nshould companies be blocked i  releasing videocards that consume.more than 150wats? \nor cpu with no more than 65?",
        "created": "2020-08-07",
        "comment": "In the summer I would say wattage is quite significant, especially when the weather is hot enough to require you to trun on the AC to cool all that heat. \n\nThe mega computation (and also the wattage) that some of these high powered GPU's is crazy in my opinion. \n\nIt's not that rare that  people put 600W+ power supplies and pull ~500W on a gaming system. In the winter that makes a great space heater, but in the summer that number really adds up fast (it's about the same as the wattage that a window AC unit pulls).  \n\nUnless you have an efficient 720p oriented system, take a summer break from desktop gaming. An xbox or efficient APU system pull ~100W\n\nYou can still do laptop gaming and explore some other gaming genres that don't pull those crazy amounts of GPU computation. Eg strategy gaming, retro gaming, sims, etc. A laptop typically pulls under 50W, including losses to heat at the power supply.",
        "is_same_stance": "T",
        "author_leaning": "R"
    },
    {
        "no": "2",
        "title": "Question about us gamers",
        "score": "2",
        "id": "i5a7p5",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i5a7p5/question_about_us_gamers/",
        "num_comments": "18",
        "body": "Does the power consumption we have on our builds affect this?\n\nor are we all just a drop of water in a big bucket.\n\ni mean i see some pc builds whose power consumption goes up to almost if not a KW \n\nshould companies be blocked i  releasing videocards that consume.more than 150wats? \nor cpu with no more than 65?",
        "created": "2020-08-07",
        "comment": "I have full wind power energy supplied at my place. I might still draw more power than I need sometimes but this is how I don't feel guilty about it. It's not expensive either. I hope it's an option where you live.",
        "is_same_stance": "T",
        "author_leaning": "R"
    },
    {
        "no": "3",
        "title": "Question about us gamers",
        "score": "2",
        "id": "i5a7p5",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i5a7p5/question_about_us_gamers/",
        "num_comments": "18",
        "body": "Does the power consumption we have on our builds affect this?\n\nor are we all just a drop of water in a big bucket.\n\ni mean i see some pc builds whose power consumption goes up to almost if not a KW \n\nshould companies be blocked i  releasing videocards that consume.more than 150wats? \nor cpu with no more than 65?",
        "created": "2020-08-07",
        "comment": "Yes, I'd say the power consumption from gaming is something to consider seriously. Consider also the reason for the power consumption: it's largely about graphics. Yet you can have equally fun play experiences with games that have far simpler graphics (you only need to look at retro indie games to realise that). Games are very seductive, and I have always loved them. But really, there are infinite ways to entertain ourselves in a very rich and satisfying way, or even a quick and easy way, that don't even use a computer. Some of them are even good for our health too! But back to the main point: the amount of CO2 production that goes into running gaming machines, let alone that which goes into manufacturing the hardware itself, is probably one of the more significant single sources of CO2 footprint that an individual has outside of a car and food. Worth thinking more about. If you wanted to get into it, you could probably do a rough calculation of the CO2 footprint for gaming and make a side by side comparison with the CO2 footprint of various other things we do or own. Shouldn't be that hard to begin building some kind of picture of this.",
        "is_same_stance": "T",
        "author_leaning": "R"
    },
    {
        "no": "4",
        "title": "Where can I read the most unbiased, factual turn of events regarding the Mann vs Ball lawsuit?",
        "score": "2",
        "id": "i4oddo",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i4oddo/where_can_i_read_the_most_unbiased_factual_turn/",
        "num_comments": "24",
        "body": "Both sides of the matter skew the story to their side, so I'm looking for the most factual representation of the matter. The court documents doesn't really explain what happened outside the court, and the lingo can be hard to understand sometimes.\n\ntldr: ELI not a law student - the most factual representation of the Mann v Ball lawsuit.",
        "created": "2020-08-06",
        "comment": "Maybe in the court documents :\n\n[https://www.bccourts.ca/jdb-txt/sc/19/15/2019BCSC1580.htm](https://www.bccourts.ca/jdb-txt/sc/19/15/2019BCSC1580.htm)\n\nDon't see that there's much complicated about the case though, or that the lingo should be overly complicated.\n\nI find the whole case rather stupid, and the discussion around it over-enthusiastic (it seems to be discussed mostly in the company of climate skeptics), even though I can understand some of the personal motivations behind it.",
        "is_same_stance": "F",
        "author_leaning": "L"
    },
    {
        "no": "5",
        "title": "NSIDC: Arctic sea-ice new record low for the month of July",
        "score": "35",
        "id": "i488cd",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i488cd/nsidc_arctic_seaice_new_record_low_for_the_month/",
        "num_comments": "1",
        "body": "[https://i.imgur.com/7xqXEdR.jpg](https://i.imgur.com/7xqXEdR.jpg)\n\nSince about ten days, loss rates slowed and we can hope there will not be a new absolute minimum later this year.\n\nInteractive Arctic / Antarctic graphs [here](https://nsidc.org/arcticseaicenews/charctic-interactive-sea-ice-graph/)  \n\nNews [here](http://nsidc.org/arcticseaicenews/)\n\n&#x200B;\n\n>(August 4, 2020) **Steep decline sputters out** The fast pace of ice loss observed in the beginning of July continued through the third week of July, after which the ice loss rates slowed dramatically. Above-average air temperatures and extensive melt pond development helped to keep the overall sea ice extent at record low levels, however, leading to a new record low for the month of July. Toward the end of the month, a strong low pressure system moved into the ice in the Beaufort Sea region. Antarctic sea ice extent remains below average levels as it climbs towards its seasonal maximum, which is typically reached in early October.",
        "created": "2020-08-05",
        "comment": "While the extent is looking better, last I heard the total volume wasn\u2019t looking as good.\n\nEdit: https://forum.arctic-sea-ice.net/index.php/topic,3017.4500.html",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "6",
        "title": "Most reliable energy",
        "score": "0",
        "id": "i3m2m0",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i3m2m0/most_reliable_energy/",
        "num_comments": "3",
        "body": "[removed]\n\n[View Poll](https://www.reddit.com/poll/i3m2m0)",
        "created": "2020-08-04",
        "comment": "No nuclear?",
        "is_same_stance": "F",
        "author_leaning": ""
    },
    {
        "no": "7",
        "title": "Most reliable energy",
        "score": "0",
        "id": "i3m2m0",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i3m2m0/most_reliable_energy/",
        "num_comments": "3",
        "body": "[removed]\n\n[View Poll](https://www.reddit.com/poll/i3m2m0)",
        "created": "2020-08-04",
        "comment": " Bruh I ran out of options that would make me have an entire new pole",
        "is_same_stance": "T",
        "author_leaning": ""
    },
    {
        "no": "8",
        "title": "See how climate change has affected where you live",
        "score": "24",
        "id": "i3dssz",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i3dssz/see_how_climate_change_has_affected_where_you_live/",
        "num_comments": "7",
        "body": "I created this web-app and thought some people in this sub might find it interesting. Allows you to look up how temperature has changed in the last 40 years for any location in the world.\n\nhttps://climate-explorer.oikolab.com/\n\nData is drawn from ERA5 reanalysis dataset (gridded 0.25 x 0.25) from ECMWF.",
        "created": "2020-08-04",
        "comment": "Thank you",
        "is_same_stance": "T",
        "author_leaning": "N"
    },
    {
        "no": "9",
        "title": "See how climate change has affected where you live",
        "score": "24",
        "id": "i3dssz",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i3dssz/see_how_climate_change_has_affected_where_you_live/",
        "num_comments": "7",
        "body": "I created this web-app and thought some people in this sub might find it interesting. Allows you to look up how temperature has changed in the last 40 years for any location in the world.\n\nhttps://climate-explorer.oikolab.com/\n\nData is drawn from ERA5 reanalysis dataset (gridded 0.25 x 0.25) from ECMWF.",
        "created": "2020-08-04",
        "comment": "My city went from 14.5 to 15.3 from the 80s to 2000, then ten years of stable weather until 2010 and a little bit of warming up to 15.5 degrees Celsius today. According to other sources the last three years have been cooler than average.",
        "is_same_stance": "T",
        "author_leaning": "N"
    },
    {
        "no": "10",
        "title": "See how climate change has affected where you live",
        "score": "24",
        "id": "i3dssz",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i3dssz/see_how_climate_change_has_affected_where_you_live/",
        "num_comments": "7",
        "body": "I created this web-app and thought some people in this sub might find it interesting. Allows you to look up how temperature has changed in the last 40 years for any location in the world.\n\nhttps://climate-explorer.oikolab.com/\n\nData is drawn from ERA5 reanalysis dataset (gridded 0.25 x 0.25) from ECMWF.",
        "created": "2020-08-04",
        "comment": "I've been running a weather station on my property for about 15 years now....I'll pull the numbers, see if there are any trends.\n\nIt *feels* cooler to me, for what it's worth, but actual data will tell.",
        "is_same_stance": "T",
        "author_leaning": "N"
    },
    {
        "no": "11",
        "title": "Suspicious Rising Levels",
        "score": "4",
        "id": "i3dgc8",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i3dgc8/suspicious_rising_levels/",
        "num_comments": "13",
        "body": "Water expands when in freezing temperature, wouldn't the water levels drop instead of increase?",
        "created": "2020-08-04",
        "comment": "If an iceberg floating in the ocean melts, it doesn\u2019t change the sea level at all. The volume of the equivalent water turns out to be the same as the volume of ice that was below the water line.\n\nBut if a glacier on land melts, and that water flows into the ocean... that\u2019s how you get sea level rise. It turns out there\u2019s a lot of water locked up in glaciers.",
        "is_same_stance": "T",
        "author_leaning": "N"
    },
    {
        "no": "12",
        "title": "Suspicious Rising Levels",
        "score": "4",
        "id": "i3dgc8",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i3dgc8/suspicious_rising_levels/",
        "num_comments": "13",
        "body": "Water expands when in freezing temperature, wouldn't the water levels drop instead of increase?",
        "created": "2020-08-04",
        "comment": "Firstly, your opening statement is only partially correct. Water \"expands\" slightly below 4 degrees Celsius but expands more at higher temperatures.\n\nSecondly, you have to consider that water in the ocean is largely incompressible and will occupy mostly the same volume regardless of pressure and that the majority of the ocean is significantly warmer than 4 degrees Celsius.\n\nThirdly, floating ice displaces an equivalent volume of water as that released when it melts, producing no sea level rise. While land-bound ice does not displace water and contributes to sea level rise upon melting.\n\nFinally, in areas of with kilometres of ice, such as Greenland and Antarctica, the continental crust of the Earth's surface is depressed by the weight of the ice which also causes other areas to be pushed up, a bit like a fulcrum or see-saw.\n\nTherefore, when land ice melts, it contributes to sea level rise while global temperatures rise causing some minor expansion of the oceans and land rises and falls on different areas.\n\n\nWhy is this nonsense post allowed in r/climatechange?",
        "is_same_stance": "T",
        "author_leaning": "N"
    },
    {
        "no": "13",
        "title": "Suspicious Rising Levels",
        "score": "4",
        "id": "i3dgc8",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i3dgc8/suspicious_rising_levels/",
        "num_comments": "13",
        "body": "Water expands when in freezing temperature, wouldn't the water levels drop instead of increase?",
        "created": "2020-08-04",
        "comment": "4\u00b0C is the temperature at which water molecules are closest to each others. Go below that and water will expand. Go above that.... And water will expand! \n\nIt seems counterintuitive, but it's really just how hydrogen bonds between water molecules work. Water is a really weird molecule. It's literally the fucking weirdo of molecules. And thankfully so: its weirdness is what makes life possible.",
        "is_same_stance": "T",
        "author_leaning": "N"
    },
    {
        "no": "14",
        "title": "Suspicious Rising Levels",
        "score": "4",
        "id": "i3dgc8",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i3dgc8/suspicious_rising_levels/",
        "num_comments": "13",
        "body": "Water expands when in freezing temperature, wouldn't the water levels drop instead of increase?",
        "created": "2020-08-04",
        "comment": "Here is an article from NASA that explains rising sea levels. [NASA](https://climate.nasa.gov/faq/30/if-all-of-earths-ice-melts-and-flows-into-the-ocean-what-would-happen-to-the-planets-rotation/) It reads that no sea ice melt will raise levels of the ocean bc of displacement, but if all the land ice melted and all of it flowed into the ocean, the ocean levels would go up about 7 meters (23 feet).",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "15",
        "title": "Suspicious Rising Levels",
        "score": "4",
        "id": "i3dgc8",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i3dgc8/suspicious_rising_levels/",
        "num_comments": "13",
        "body": "Water expands when in freezing temperature, wouldn't the water levels drop instead of increase?",
        "created": "2020-08-04",
        "comment": "At the end of the last ice age the temperature rose about 5C degrees and the sea level rose about 400 feet because of melting ice and water expansion. Simple evidence.",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "16",
        "title": "China continues to increase its coal power, new projects account for 90% of the global total.",
        "score": "88",
        "id": "i2z0ok",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i2z0ok/china_continues_to_increase_its_coal_power_new/",
        "num_comments": "28",
        "body": "https://pvbuzz.com/china-increase-coal-power/\n\nChina has built more than half of the world\u2019s new coal power plants this year and accounted for 90 percent of new planned capacity.",
        "created": "2020-08-03",
        "comment": "CarbonBrief published an article on this.\n\n[Analysis: The global coal fleet shrank for first time on record in 2020](https://www.carbonbrief.org/analysis-the-global-coal-fleet-shrank-for-first-time-on-record-in-2020)",
        "is_same_stance": "T",
        "author_leaning": "N"
    },
    {
        "no": "17",
        "title": "China continues to increase its coal power, new projects account for 90% of the global total.",
        "score": "88",
        "id": "i2z0ok",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i2z0ok/china_continues_to_increase_its_coal_power_new/",
        "num_comments": "28",
        "body": "https://pvbuzz.com/china-increase-coal-power/\n\nChina has built more than half of the world\u2019s new coal power plants this year and accounted for 90 percent of new planned capacity.",
        "created": "2020-08-03",
        "comment": "And here in Australia we\u2019re shutting down our coal plants, suffering blackouts, watching power prices skyrocket, and watching all our business move to China.",
        "is_same_stance": "T",
        "author_leaning": "N"
    },
    {
        "no": "18",
        "title": "China continues to increase its coal power, new projects account for 90% of the global total.",
        "score": "88",
        "id": "i2z0ok",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i2z0ok/china_continues_to_increase_its_coal_power_new/",
        "num_comments": "28",
        "body": "https://pvbuzz.com/china-increase-coal-power/\n\nChina has built more than half of the world\u2019s new coal power plants this year and accounted for 90 percent of new planned capacity.",
        "created": "2020-08-03",
        "comment": "Even during the pandemic",
        "is_same_stance": "T",
        "author_leaning": "N"
    },
    {
        "no": "19",
        "title": "China continues to increase its coal power, new projects account for 90% of the global total.",
        "score": "88",
        "id": "i2z0ok",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i2z0ok/china_continues_to_increase_its_coal_power_new/",
        "num_comments": "28",
        "body": "https://pvbuzz.com/china-increase-coal-power/\n\nChina has built more than half of the world\u2019s new coal power plants this year and accounted for 90 percent of new planned capacity.",
        "created": "2020-08-03",
        "comment": "We already knew this. Why do new reports about it have to be published all the time",
        "is_same_stance": "T",
        "author_leaning": "N"
    },
    {
        "no": "20",
        "title": "China continues to increase its coal power, new projects account for 90% of the global total.",
        "score": "88",
        "id": "i2z0ok",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i2z0ok/china_continues_to_increase_its_coal_power_new/",
        "num_comments": "28",
        "body": "https://pvbuzz.com/china-increase-coal-power/\n\nChina has built more than half of the world\u2019s new coal power plants this year and accounted for 90 percent of new planned capacity.",
        "created": "2020-08-03",
        "comment": "This is quite short-term reporting here. For climate, maybe longer-term reporting from the likes of IEA are of interest. They also give context to current covid trends :\n\n [https://www.iea.org/reports/global-energy-review-2020/coal](https://www.iea.org/reports/global-energy-review-2020/coal)",
        "is_same_stance": "T",
        "author_leaning": "N"
    },
    {
        "no": "21",
        "title": "China continues to increase its coal power, new projects account for 90% of the global total.",
        "score": "88",
        "id": "i2z0ok",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i2z0ok/china_continues_to_increase_its_coal_power_new/",
        "num_comments": "28",
        "body": "https://pvbuzz.com/china-increase-coal-power/\n\nChina has built more than half of the world\u2019s new coal power plants this year and accounted for 90 percent of new planned capacity.",
        "created": "2020-08-03",
        "comment": " But here In The US we are banning straws and plastic bags. \n\nPeople tend to forget that gross co2 emissions are all that matter. Per capita emissions are irrelevant to a changing climate. \n\nIn other words, spending time lobbying China is far better resources than spending time chasing lightbulbs and plastic in the US, or any other western nation.",
        "is_same_stance": "T",
        "author_leaning": "N"
    },
    {
        "no": "22",
        "title": "Temperatures on a mountain top vs the valley",
        "score": "2",
        "id": "i2j6v3",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i2j6v3/temperatures_on_a_mountain_top_vs_the_valley/",
        "num_comments": "5",
        "body": "I spent the weekend in a mountain top. I am concerned that the top was only 2 - 4 degrees cooler than then valley floor with a difference of 4,000 feet between the valley floor and the mountain. It was never this way 40 years ago when we would go on the mountain to get out of the heat. What is going on? Are the warm temperatures just getting thicker?",
        "created": "2020-08-02",
        "comment": "Confirmation bias mixed with small sample size.  Masses of air shift, and  it isn't actually unusual to have a warm air mass over the top of a cooler one.  In general, the lapse rate hasn't changed.",
        "is_same_stance": "F",
        "author_leaning": "L"
    },
    {
        "no": "23",
        "title": "Temperatures on a mountain top vs the valley",
        "score": "2",
        "id": "i2j6v3",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i2j6v3/temperatures_on_a_mountain_top_vs_the_valley/",
        "num_comments": "5",
        "body": "I spent the weekend in a mountain top. I am concerned that the top was only 2 - 4 degrees cooler than then valley floor with a difference of 4,000 feet between the valley floor and the mountain. It was never this way 40 years ago when we would go on the mountain to get out of the heat. What is going on? Are the warm temperatures just getting thicker?",
        "created": "2020-08-02",
        "comment": "No, this is definitely not a legitimate measure and is purely anecdotal.\n\nI lived in Colorado. I went from hiking a 14er in July back to Denver, and the temperature went from 42F in the little mountain nearby to Denver\u2019s 95F+.\n\nI lived in Utah. The mountains I would climate were around 5,000 ft higher than our living altitude. The temperatures were technically \u2018cooler\u2019 on top of the mountain - but 99 in the valley still translates to about 80-85 on top of a 10k peak with incredibly intense sunlight.\n\nThis will be even less noticeable somewhere like the southern Appalachians (or even most of Appalachia in the summer).\n\nTLDR - No, the basic concept of atmospheric science still exists and is intact. You will always lose 3-4\u00b0 per 1000 ft of altitude gained. If it is hot on the top of a mountain, it is even hotter below.\n\nhttps://www.google.com/amp/s/treelinebackpacker.com/2013/05/06/calculate-temperature-change-with-elevation/amp/",
        "is_same_stance": "F",
        "author_leaning": "L"
    },
    {
        "no": "24",
        "title": "Innovative methods for cities/towns to help?",
        "score": "3",
        "id": "i1fki8",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i1fki8/innovative_methods_for_citiestowns_to_help/",
        "num_comments": "1",
        "body": "I recently found out that France actually had a potential law in place to mandate green roofs (either solar panels or grass rooftops) for all commercial buildings but sadly got passed down. I was really disappointed to hear that (even though it was a few years ago) because it truly seemed like a great idea and wouldn't have been that expensive, especially as solar panels would've ended up saving money for companies in the long run. \n\nWhile this didn't work for France, do you guys think that it would work for a not so large city or a town to adopt this? If not, what are some other innovative methods for cities and towns to reduce emissions or help with climate change without being too costly?\n\nI would love to learn about some new ideas that exist or other cities have taken to be more environmentally friendly. \n\n(side note: I've worked with my local county in the past with addressing homeless so I'm familiar with how local government. I have some free time nowadays and really would like to learn more about addressing climate change. I myself try to be eco-friendly and as sustainable as possible but would love something more on a larger scale.)",
        "created": "2020-07-31",
        "comment": "Since you\u2019re familiar with local government I think checking out C40 cities or the Covenant of mayors will yield good resources \n\nBut off the top of my head:\n\n1) Dimming street lights later at night, assuming it\u2019s possible to control \n\n2) Partner with a trash-to-hydrogen company (Lancaster, CA)\n\n3) If vehicle fleet is leased, go electric \n\n4) Ban new natural gas connections(assuming there is the jurisdiction to do so)\n\nI\u2019m not sure if you\u2019re asking for small cities or cities as a whole though \n\nNew York City  did actually do what you mentioned earlier, mandating green roofs or rooftop renewables in new construction",
        "is_same_stance": "T",
        "author_leaning": "N"
    },
    {
        "no": "25",
        "title": "How scared are you about global warming and why?",
        "score": "8",
        "id": "i168qz",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i168qz/how_scared_are_you_about_global_warming_and_why/",
        "num_comments": "36",
        "body": "How scared are you from one to ten, where one is \"I don't care\" and ten is \"I'm extremely scared and it causes me crippling anxiety and I might build a bunker or something\"? Can you explain why?\n\n(Negative numbers will be interpreted as skepticism)\n\nAlso how imminent of a threat do you perceive it to be?",
        "created": "2020-07-31",
        "comment": "Not sure what number to allocate this on the scale you described.\n\nI believe we are experiencing climate change and I care about reducing the future impact, but I experience nor feel any fear or anxiety?\n\nAs to how imminent, it is happening, has been happening for a long time, will continue to happen with variable severity depending on our present actions and decisions. These are all things which have been and are being advocated and voiced by scientists. The impact on your life depends on where you live but by no means is it a future event. The climate has changed and people do suffer as a result.",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "26",
        "title": "How scared are you about global warming and why?",
        "score": "8",
        "id": "i168qz",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i168qz/how_scared_are_you_about_global_warming_and_why/",
        "num_comments": "36",
        "body": "How scared are you from one to ten, where one is \"I don't care\" and ten is \"I'm extremely scared and it causes me crippling anxiety and I might build a bunker or something\"? Can you explain why?\n\n(Negative numbers will be interpreted as skepticism)\n\nAlso how imminent of a threat do you perceive it to be?",
        "created": "2020-07-31",
        "comment": "Hard to put a number on it but I guess maybe a 5. I try to do something myself, stay informed, and discuss the issue. I think it's quite possible for us to still turn the boat around. I'm an avid believer in the old wisdom that people underestimate long-term change and overestimate short-term change. \n\nAnd then I don't think it's so imminent that the short-term would be cataclysmic - the threat is more if we don't manage to move in 20 - 60 years, which I think we might well manage.",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "27",
        "title": "How scared are you about global warming and why?",
        "score": "8",
        "id": "i168qz",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i168qz/how_scared_are_you_about_global_warming_and_why/",
        "num_comments": "36",
        "body": "How scared are you from one to ten, where one is \"I don't care\" and ten is \"I'm extremely scared and it causes me crippling anxiety and I might build a bunker or something\"? Can you explain why?\n\n(Negative numbers will be interpreted as skepticism)\n\nAlso how imminent of a threat do you perceive it to be?",
        "created": "2020-07-31",
        "comment": "This is an odd way to frame this question. And 0 should be skeptics, why would the scale go negative... lol?\n\nFor my own lifetime: 2. I\u2019ll be homesteading in a climate-resilient place near fresh water. I\u2019m over thirty in the developed west; nearly all legitimate climate science points to my life not being affected drastically, other than my love for snowboarding.\n\nFor other\u2019s current lifetimes: 5. This has more to do with poorer nations than anything. The west (outside of Australia) will largely be spared from majorly life-altering effects. The plus side is poorer nations continue to develop which means better overall resiliency. But heat waves, air pollution and local pollution are still bigger concerns for these places in the semi-near term.\n\nFor the future humans beyond 2100 - 6. I think we are on a downward curve, largely not for the better in terms of ecosystems. But it *is* salvageable, we *are* actually doing really great things around the world, and we have some Hail Marys that are certainly worth a shot if we\u2019re not able to really wrestle down emissions over the next 2-3 decades, and develop better large-scale projects for carbon capture. I think we have enough great minds, especially with younger generations, to mitigate most of the worst.\n\nInb4 something about hopium or BOE or IPCC being too conservative \ud83d\ude44",
        "is_same_stance": "T",
        "author_leaning": "N"
    },
    {
        "no": "28",
        "title": "How scared are you about global warming and why?",
        "score": "8",
        "id": "i168qz",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i168qz/how_scared_are_you_about_global_warming_and_why/",
        "num_comments": "36",
        "body": "How scared are you from one to ten, where one is \"I don't care\" and ten is \"I'm extremely scared and it causes me crippling anxiety and I might build a bunker or something\"? Can you explain why?\n\n(Negative numbers will be interpreted as skepticism)\n\nAlso how imminent of a threat do you perceive it to be?",
        "created": "2020-07-31",
        "comment": "As far as feeling an emotional fear? Near zero. One of many abstract concerns about human wellbeing in general. I agree with the general scientific consensus on global warming. To some people I'm still an \"alarmist,\" go figure.\n\nGlobal warming is already happening, so I'd say \"imminent\" is not the greatest description.",
        "is_same_stance": "T",
        "author_leaning": "N"
    },
    {
        "no": "29",
        "title": "How scared are you about global warming and why?",
        "score": "8",
        "id": "i168qz",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i168qz/how_scared_are_you_about_global_warming_and_why/",
        "num_comments": "36",
        "body": "How scared are you from one to ten, where one is \"I don't care\" and ten is \"I'm extremely scared and it causes me crippling anxiety and I might build a bunker or something\"? Can you explain why?\n\n(Negative numbers will be interpreted as skepticism)\n\nAlso how imminent of a threat do you perceive it to be?",
        "created": "2020-07-31",
        "comment": "Climate changes ranks probably around a 4 or 5 for me its like a low key nagging worry that I get reminded about weekly.\n\nIt will steadily go up, im in the demographic set to retire at around 2050. So instead of a nice happy retirement, im looking forward to extensive famines, large areas of the world becoming unhospitable, wars over basic resources being common place, massive overpopulation and migration and the near complete destruction of a majority of ecosystems.\n\nTrying to do my but to drastically reduce my strain on the world but with current levels of stupidity around the world right now i dont have hope.\n\nCatch me in ten years where i'll probably be getting my hobbit hole ready",
        "is_same_stance": "T",
        "author_leaning": "N"
    },
    {
        "no": "30",
        "title": "How scared are you about global warming and why?",
        "score": "8",
        "id": "i168qz",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i168qz/how_scared_are_you_about_global_warming_and_why/",
        "num_comments": "36",
        "body": "How scared are you from one to ten, where one is \"I don't care\" and ten is \"I'm extremely scared and it causes me crippling anxiety and I might build a bunker or something\"? Can you explain why?\n\n(Negative numbers will be interpreted as skepticism)\n\nAlso how imminent of a threat do you perceive it to be?",
        "created": "2020-07-31",
        "comment": "Strange scale to me. I am not the least scared, the climate varies and I do not think anyone can do anything about it as I think it is fractionally and insignificantly caused by co2.\nOf course I care though. What no. does this represent?\n1?\nI am though worried/concerned about the global environment issues, waste, contamination of oceans, particulate emissions etc. This is rarely mentionned in the co2 media frenzy....\nAnd also: I am also concerned about the 100's of millions starving poor people of the world who might die from this zero-co2 propaganda from lack of energy and food.",
        "is_same_stance": "T",
        "author_leaning": "N"
    },
    {
        "no": "31",
        "title": "How scared are you about global warming and why?",
        "score": "8",
        "id": "i168qz",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i168qz/how_scared_are_you_about_global_warming_and_why/",
        "num_comments": "36",
        "body": "How scared are you from one to ten, where one is \"I don't care\" and ten is \"I'm extremely scared and it causes me crippling anxiety and I might build a bunker or something\"? Can you explain why?\n\n(Negative numbers will be interpreted as skepticism)\n\nAlso how imminent of a threat do you perceive it to be?",
        "created": "2020-07-31",
        "comment": "When asked this 30 years ago I was pretty concerned.  But I was told we would be underwater and my beachfront house would be gone. Polar bears would be gone, the ice caps would be gone, kids wouldn't know what snow is and all sorts of other nonsense that never came to pass.  \n\nSo at this stage your scale is meaninglessness because 1 being I don't care isn't representative.\n\nI do care but I just know better from both my own experience and my parents and grandparents experience. \n\nWe have never had it so good. Ever.",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "32",
        "title": "How scared are you about global warming and why?",
        "score": "8",
        "id": "i168qz",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i168qz/how_scared_are_you_about_global_warming_and_why/",
        "num_comments": "36",
        "body": "How scared are you from one to ten, where one is \"I don't care\" and ten is \"I'm extremely scared and it causes me crippling anxiety and I might build a bunker or something\"? Can you explain why?\n\n(Negative numbers will be interpreted as skepticism)\n\nAlso how imminent of a threat do you perceive it to be?",
        "created": "2020-07-31",
        "comment": "8.5\n\nIt is my main cause of worry. \n\nIt is not imminent. But that is part of the problem. This is a huge problem with a great amount of physical inertia. Because it is not imminent we will not be able to react in time to prevent it from becoming imminent and pass way beyond that. Arguably it is already to late to react to fully prevent catastrophic consequences. All we can do now is influence how bad it will be. Hopefully we are still able to prevent or mitigate the worst dangers. Hopefully. \n\nAnd we already see and experience problems that are directly or indirectly linked to climate change. \n\nI have changed my lifestyle radically to lower my own CO2 footprint. I also make sure that land and forest I own work as carbon sinks. Mainly by allowing the soil to increase the carbon contents. You could say that I already live in the bunker. But it is a pretty nice bunker then. A farm deep inside the southern woods of Sweden. Cycling distance (if you are fit) from the nearest town. Depending on how you count, I personally may have a negative CO2 footprint with my current lifestyle. But not seen over my whole life... \n\nI feel very privileged, because I am able to live a rich, happy and enjoyable life, without a lot of personal worries.",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "33",
        "title": "How scared are you about global warming and why?",
        "score": "8",
        "id": "i168qz",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i168qz/how_scared_are_you_about_global_warming_and_why/",
        "num_comments": "36",
        "body": "How scared are you from one to ten, where one is \"I don't care\" and ten is \"I'm extremely scared and it causes me crippling anxiety and I might build a bunker or something\"? Can you explain why?\n\n(Negative numbers will be interpreted as skepticism)\n\nAlso how imminent of a threat do you perceive it to be?",
        "created": "2020-07-31",
        "comment": "9.9?  Not \"crippling \" anxiety,  but definitely anxious.  The combination of too many people with a decreasing food base (from drought, flooding, extreme weather) pretty much guarantees an ugly result.  I don't have a bunker,  but do have a cabin up north with some supplies. \nIt's just so stupid and depressing,  like the covid pandemic,  just a little foresight and planning we could deal. But NOOOOOOO! Someone might not make as much profit! Can't have THAT!",
        "is_same_stance": "T",
        "author_leaning": "N"
    },
    {
        "no": "34",
        "title": "How scared are you about global warming and why?",
        "score": "8",
        "id": "i168qz",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i168qz/how_scared_are_you_about_global_warming_and_why/",
        "num_comments": "36",
        "body": "How scared are you from one to ten, where one is \"I don't care\" and ten is \"I'm extremely scared and it causes me crippling anxiety and I might build a bunker or something\"? Can you explain why?\n\n(Negative numbers will be interpreted as skepticism)\n\nAlso how imminent of a threat do you perceive it to be?",
        "created": "2020-07-31",
        "comment": "I'm more concerned than scared, so probably around a 6 or 7. I've mostly accepted that things will get really bad and try to organize my life in a way that accounts for that. \n\nThe threat is extremely imminent. It's already seriously affecting parts of the world. They just happen to be parts of the world that aren't the USA or Europe so most people aren't paying attention.",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "35",
        "title": "How scared are you about global warming and why?",
        "score": "8",
        "id": "i168qz",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i168qz/how_scared_are_you_about_global_warming_and_why/",
        "num_comments": "36",
        "body": "How scared are you from one to ten, where one is \"I don't care\" and ten is \"I'm extremely scared and it causes me crippling anxiety and I might build a bunker or something\"? Can you explain why?\n\n(Negative numbers will be interpreted as skepticism)\n\nAlso how imminent of a threat do you perceive it to be?",
        "created": "2020-07-31",
        "comment": "7 or 8\n\nIt makes literally everything, the sum of history and the future of my family, feel futile. All of the achievements of humanity, our efforts, our triumphs, our successes, our beauty and wonderful accomplishments, ultimately led to mass extinction, death, and irreversible devastation. Taking our privileged paradise of a planet and breaking it beyond repair. It's humiliating.",
        "is_same_stance": "T",
        "author_leaning": "N"
    },
    {
        "no": "36",
        "title": "How scared are you about global warming and why?",
        "score": "8",
        "id": "i168qz",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i168qz/how_scared_are_you_about_global_warming_and_why/",
        "num_comments": "36",
        "body": "How scared are you from one to ten, where one is \"I don't care\" and ten is \"I'm extremely scared and it causes me crippling anxiety and I might build a bunker or something\"? Can you explain why?\n\n(Negative numbers will be interpreted as skepticism)\n\nAlso how imminent of a threat do you perceive it to be?",
        "created": "2020-07-31",
        "comment": "I'm well aware of it on a daily basis but I've accepted it. I'm not afraid...but I'm sure when I don't have food or something like that I will feel it a lot worse especially for my kid",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "37",
        "title": "How scared are you about global warming and why?",
        "score": "8",
        "id": "i168qz",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i168qz/how_scared_are_you_about_global_warming_and_why/",
        "num_comments": "36",
        "body": "How scared are you from one to ten, where one is \"I don't care\" and ten is \"I'm extremely scared and it causes me crippling anxiety and I might build a bunker or something\"? Can you explain why?\n\n(Negative numbers will be interpreted as skepticism)\n\nAlso how imminent of a threat do you perceive it to be?",
        "created": "2020-07-31",
        "comment": "7\n\nReason:  1.) I'm pale as fuck and it's currently 37\u00b0C - it was never that hot; 2.) It's reasonable to assume that people in 2100 won't be able to permanently live in the northern part of South America - it'll be hot and humid. (I've watched an extremely well made and convincing presentation about meta research of all climate research.)",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "38",
        "title": "How scared are you about global warming and why?",
        "score": "8",
        "id": "i168qz",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i168qz/how_scared_are_you_about_global_warming_and_why/",
        "num_comments": "36",
        "body": "How scared are you from one to ten, where one is \"I don't care\" and ten is \"I'm extremely scared and it causes me crippling anxiety and I might build a bunker or something\"? Can you explain why?\n\n(Negative numbers will be interpreted as skepticism)\n\nAlso how imminent of a threat do you perceive it to be?",
        "created": "2020-07-31",
        "comment": "4\n\n\"How imminent\" suggests that this is in the future, but it is already happening with observable effects on many species e.g. bees.",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "39",
        "title": "How scared are you about global warming and why?",
        "score": "8",
        "id": "i168qz",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i168qz/how_scared_are_you_about_global_warming_and_why/",
        "num_comments": "36",
        "body": "How scared are you from one to ten, where one is \"I don't care\" and ten is \"I'm extremely scared and it causes me crippling anxiety and I might build a bunker or something\"? Can you explain why?\n\n(Negative numbers will be interpreted as skepticism)\n\nAlso how imminent of a threat do you perceive it to be?",
        "created": "2020-07-31",
        "comment": "Probably somewhere around 1e-6. I believe in climate change, but vehemently disagree with climate change alarmists.",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "40",
        "title": "How scared are you about global warming and why?",
        "score": "8",
        "id": "i168qz",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i168qz/how_scared_are_you_about_global_warming_and_why/",
        "num_comments": "36",
        "body": "How scared are you from one to ten, where one is \"I don't care\" and ten is \"I'm extremely scared and it causes me crippling anxiety and I might build a bunker or something\"? Can you explain why?\n\n(Negative numbers will be interpreted as skepticism)\n\nAlso how imminent of a threat do you perceive it to be?",
        "created": "2020-07-31",
        "comment": "Have you noticed that global warming is cancelled out?",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "41",
        "title": "Looking for charities that help climate refugees?",
        "score": "6",
        "id": "i10hhc",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i10hhc/looking_for_charities_that_help_climate_refugees/",
        "num_comments": "2",
        "body": "It can be based anywhere in the world - I just want an organization that actually helps climate refugees (as opposed to high-level policy or advocacy). Everything I've found so far is purely educational or focuses on refugees fleeing from war and conflict.",
        "created": "2020-07-31",
        "comment": "It's my understanding that climate refugees are mostly projected for the future. \n\nProbably a lot of other charities you could donate to though. I think clean cooking in poor countries would be one tangible thing. It should save firewood resources in poor countries and be a health benefit to the people.\n\nhttps://isnad-africa.org/2019/02/04/cleaner-cooking-and-its-role-in-africas-future/",
        "is_same_stance": "T",
        "author_leaning": "N"
    },
    {
        "no": "42",
        "title": "U.S. coal production is down to its lowest level in four decades.",
        "score": "101",
        "id": "i0kven",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i0kven/us_coal_production_is_down_to_its_lowest_level_in/",
        "num_comments": "4",
        "body": "https://pvbuzz.com/story/coal-production-fell-lowest-level/\n \nThis further indicates a decline of American coal mining as it faces stiffer competition from cleaner and cheaper sources of power.",
        "created": "2020-07-30",
        "comment": "That's mostly natural gas. While gas is indeed cleaner and cheaper than coal, there are still plenty of problems with it.",
        "is_same_stance": "T",
        "author_leaning": "N"
    },
    {
        "no": "43",
        "title": "U.S. coal production is down to its lowest level in four decades.",
        "score": "101",
        "id": "i0kven",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i0kven/us_coal_production_is_down_to_its_lowest_level_in/",
        "num_comments": "4",
        "body": "https://pvbuzz.com/story/coal-production-fell-lowest-level/\n \nThis further indicates a decline of American coal mining as it faces stiffer competition from cleaner and cheaper sources of power.",
        "created": "2020-07-30",
        "comment": "Hows it worldwide though?",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "44",
        "title": "Is there some factor in which greenhouse gasses are absorbed in a certain time?",
        "score": "7",
        "id": "i0kpc7",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i0kpc7/is_there_some_factor_in_which_greenhouse_gasses/",
        "num_comments": "6",
        "body": "Hi all,\n\nThis is my first post on reddit so please excuse me in the case I'm breaking some (unwritten) rules here.\n\nAnyhow, I am currently writing a bachelor's thesis in the field of microeconomics and my topic is about how taxation can cause dairy producers to adjust their level of milk production, or decide to migrate to another country. The idea is, that there could be a level of taxation where dairy farmers decide to migrate to countries where production is cheaper, causing higher levels of greenhouse gas emissions. In other words - can taxes (that could be aimed at reducing greenhouse gas emissions) have a negative net-effect in overall global emissions?\n\nThe problem is, my knowledge about environmental chemistry is quite minimal and my thesis supervisor asks me to find a level of taxation where *the accumulation of greenhouse gas emissions is stable*, in other words, the amount of greenhouse gasses emitted in a year equals the amount of gasses that are absorbed/broken down in that same year.\n\nIn other words, my supervisor asks me to describe a function like:  \nS(t+1) = S(t) (1-x) + E(t+1)  \nwhere S is the level of gases in the air, and E is the emissions in that period (I have an emission function) and x is the proportion of gases that disappear. \n\nAs it is in the context of dairy farms, for simplicity's sake, I consider carbon dioxide, methane and nitrous oxide emissions. For those gasses I can find a '[atmospheric lifetime](https://www.seattle.gov/light/news/RFI_RFP/RFP_ggm_Appendix1.pdf)' which is a number of years in which gasses are expected to remain inside the atmosphere. Does that mean for any gas, I can assume that there is some type of exponential decay (regardless of the quantity of emissions)?\n\nDoes anybody know if there is a certain percentage rate of decay for those gasses?\n\nYour help is kindly regarded. If you have some title in the field of chemistry or climatology, I would be willing to acknowledge your help in my thesis, if you would like that.\n\nThanks!",
        "created": "2020-07-30",
        "comment": "Hi Tuffah,\n\nFirst off, this sounds like a pretty interesting angle on a common concept, well done with that!\n\nNow, regarding at least the CO2 in the atmosphere. It's not really correct to consider it in the same way as radioactive decay and it isn't an exponential reduction.\n\nFor chemicals such as CO2, the residence time describes how long the average molecule would be expected to exist in that reservoir of the climate system. So obviously as it is an average some will remain there for more or less time but for your purposes the residence time is sufficient.\n\nRegarding your expression in S and E, your emissions should account for the release of the greenhouse gases you describe as positive to the atmospheric reservoir and their removal by processes such as photosynthesis or dissolution as negative.\n\nSo rather than an absolute decay of the particle in the atmosphere, it's rather at which point do the emissions become net negative that your atmospheric concentration of CO2 would begin to reduce.\n\nRegarding methane and nitrous oxide, you also need to consider these positive and negative fluxes but also their decay within the atmosphere. For instance oxidation of methane to CO2. However, I think again it is the release and uptake of these chemicals between compartments that is most significant.\n\nWith regards to resources, if you search for anything relating to the carbon cycle, it will give you a good impression of the land and ocean sinks for carbon and the current estimates (the ipcc and the global carbon budget are good resources for this). I am less versed in literature sources for methane or nitrous oxide but these should be available also. I think learning some minor chemistry is unavoidable here but you don't need much depth for the purposes you described.\n\nHopefully this helps, if you have more questions feel free to contact me.",
        "is_same_stance": "T",
        "author_leaning": "N"
    },
    {
        "no": "45",
        "title": "Is there some factor in which greenhouse gasses are absorbed in a certain time?",
        "score": "7",
        "id": "i0kpc7",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i0kpc7/is_there_some_factor_in_which_greenhouse_gasses/",
        "num_comments": "6",
        "body": "Hi all,\n\nThis is my first post on reddit so please excuse me in the case I'm breaking some (unwritten) rules here.\n\nAnyhow, I am currently writing a bachelor's thesis in the field of microeconomics and my topic is about how taxation can cause dairy producers to adjust their level of milk production, or decide to migrate to another country. The idea is, that there could be a level of taxation where dairy farmers decide to migrate to countries where production is cheaper, causing higher levels of greenhouse gas emissions. In other words - can taxes (that could be aimed at reducing greenhouse gas emissions) have a negative net-effect in overall global emissions?\n\nThe problem is, my knowledge about environmental chemistry is quite minimal and my thesis supervisor asks me to find a level of taxation where *the accumulation of greenhouse gas emissions is stable*, in other words, the amount of greenhouse gasses emitted in a year equals the amount of gasses that are absorbed/broken down in that same year.\n\nIn other words, my supervisor asks me to describe a function like:  \nS(t+1) = S(t) (1-x) + E(t+1)  \nwhere S is the level of gases in the air, and E is the emissions in that period (I have an emission function) and x is the proportion of gases that disappear. \n\nAs it is in the context of dairy farms, for simplicity's sake, I consider carbon dioxide, methane and nitrous oxide emissions. For those gasses I can find a '[atmospheric lifetime](https://www.seattle.gov/light/news/RFI_RFP/RFP_ggm_Appendix1.pdf)' which is a number of years in which gasses are expected to remain inside the atmosphere. Does that mean for any gas, I can assume that there is some type of exponential decay (regardless of the quantity of emissions)?\n\nDoes anybody know if there is a certain percentage rate of decay for those gasses?\n\nYour help is kindly regarded. If you have some title in the field of chemistry or climatology, I would be willing to acknowledge your help in my thesis, if you would like that.\n\nThanks!",
        "created": "2020-07-30",
        "comment": "5.3\n\nthe answer you are after is Carbon in the Atmospheric Carbon Cycle (CarbonDioxide, Methane, other hydrocarbons) has a 5.3 year residence time.\n\nthis video explains the math and calcs that come to this figure, from 32:30 to 36:00\n\n[https://www.youtube.com/watch?v=WNEQo6lk9ko](https://www.youtube.com/watch?v=WNEQo6lk9ko)\n\nthe video cites the following references if you want to check the maths. (I also encourage you to watch the whole vid, it's a bit eye-opening)\n\nLepori, L., Bussolino, G., Matteoli, E., & Spanedda, A. On the increase of fossil CO2 in the atmosphere.\n\nSegalstad, T. V. (1998). Carbon cycle modelling and the residence time of natural and anthropogenic atmospheric CO2. BATE, R.(Ed., 1998): Global Warming, 184-219.\n\nQuirk, T. (2009). Sources and sinks of carbon dioxide. Energy & Environment, 20(1), 105-121.\n\nHarde, H. (2017). Scrutinizing the carbon cycle and CO 2 residence time in the atmosphere. Global and Planetary Change, 152, 19-26.\n\n&#x200B;\n\nhope this helps",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "46",
        "title": "Global warming from a climate sensitivity of 1.4\u00b0C (based on 24 different studies)",
        "score": "0",
        "id": "i0jhd6",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i0jhd6/global_warming_from_a_climate_sensitivity_of_14c/",
        "num_comments": "11",
        "body": "Decided to make a graph showing the warming from CO2 based on a climate sensitivity of 1.4\u00b0C (which is the average of the studies in this graph [here](https://1.bp.blogspot.com/-QKd0oR56do4/XnjLlunnIEI/AAAAAAAARTQ/aNna9JOSNUAh1-ufbP1n6JyzeeMj3WcPgCLcBGAsYHQ/s1600/infographic+(48)+(1).png) since 2011). Might update it to include the most recent estimates in 2020 later. The graph shows that for the first 20ppmv increase in CO2 in the atmosphere, the warming is about 6\u00b0C. Then the next 20ppmv, taking it up to 40ppmv is 1.4\u00b0C. When it gets to 200ppmv then 20ppmv increments are reduced to 0.2\u00b0C and when it gets to 400ppmv then 20ppmv increments are reduced to 0.1\u00b0C. It seems to me that CO2 is having a real warming effect but it is miniscule and far too small to warrant drastic measures being taken worldwide to counteract it.\n\nhttps://preview.redd.it/yebd5viqxyd51.png?width=727&format=png&auto=webp&s=65d837ee6a5e630819a1401007239d854ed3405b",
        "created": "2020-07-30",
        "comment": "I first saw the graph you attached several months ago. Climate sensitivity is estimated in three different ways, climate models, paleo records, and instrumental. It gave the source as the IPCC instrumental records but without a link and stated the instrumental records were the best without providing any evidence of that. I could not find those numbers in the IPCC. In addition it did not say whether it was an ECS or a TCR (which gives lower numbers). I did see that many of the later instrumental studies were done by climate deniers in recent organizations that they have created in order to say they have published because the major science publications can not verify their findings so will not publish their studies. \n\nThere have been hundreds of climate sensitivity studies. Since 2000 the average ECS for climate models and paleo records is 3.2C with the instrumental studies at 2.0C. Naturally climate deniers want to use the instrumental studies. \n\nBut how did you create the vertical values from a sensitivity of 1.4C?",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "47",
        "title": "Global warming from a climate sensitivity of 1.4\u00b0C (based on 24 different studies)",
        "score": "0",
        "id": "i0jhd6",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i0jhd6/global_warming_from_a_climate_sensitivity_of_14c/",
        "num_comments": "11",
        "body": "Decided to make a graph showing the warming from CO2 based on a climate sensitivity of 1.4\u00b0C (which is the average of the studies in this graph [here](https://1.bp.blogspot.com/-QKd0oR56do4/XnjLlunnIEI/AAAAAAAARTQ/aNna9JOSNUAh1-ufbP1n6JyzeeMj3WcPgCLcBGAsYHQ/s1600/infographic+(48)+(1).png) since 2011). Might update it to include the most recent estimates in 2020 later. The graph shows that for the first 20ppmv increase in CO2 in the atmosphere, the warming is about 6\u00b0C. Then the next 20ppmv, taking it up to 40ppmv is 1.4\u00b0C. When it gets to 200ppmv then 20ppmv increments are reduced to 0.2\u00b0C and when it gets to 400ppmv then 20ppmv increments are reduced to 0.1\u00b0C. It seems to me that CO2 is having a real warming effect but it is miniscule and far too small to warrant drastic measures being taken worldwide to counteract it.\n\nhttps://preview.redd.it/yebd5viqxyd51.png?width=727&format=png&auto=webp&s=65d837ee6a5e630819a1401007239d854ed3405b",
        "created": "2020-07-30",
        "comment": "Your cited research appears to be a homemade picture from a blog that is only an image with no references to scientific research. Is there more that wasn't linked?\n\n&#x200B;\n\n* Is this implying that with increased atmospheric CO2 the influence it has on global warming decreases at a determined rate?\n*  What are these calculations based off of? \n* What is your baseline level of CO2 for this graph? Current CO2 levels, pre-industrial CO2 levels? \n* Also what is climate sensitivity of 1.4 degrees? \n\nClimate sensitivity is a measure of how much the Earth's climate will cool or warm after a change in the climate system, for instance, how much it will warm for doubling in carbon dioxide concentrations. I don't understand the 1.4 degrees, is this graph stating that at 500ppm our temperature will be 1.4 degrees warmer than it is now or that an additional 500ppm to our current levels (413ppm) of atmospheric CO2 totaling 900ppm will yield a 1.4 degree increase?",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "48",
        "title": "Global warming from a climate sensitivity of 1.4\u00b0C (based on 24 different studies)",
        "score": "0",
        "id": "i0jhd6",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i0jhd6/global_warming_from_a_climate_sensitivity_of_14c/",
        "num_comments": "11",
        "body": "Decided to make a graph showing the warming from CO2 based on a climate sensitivity of 1.4\u00b0C (which is the average of the studies in this graph [here](https://1.bp.blogspot.com/-QKd0oR56do4/XnjLlunnIEI/AAAAAAAARTQ/aNna9JOSNUAh1-ufbP1n6JyzeeMj3WcPgCLcBGAsYHQ/s1600/infographic+(48)+(1).png) since 2011). Might update it to include the most recent estimates in 2020 later. The graph shows that for the first 20ppmv increase in CO2 in the atmosphere, the warming is about 6\u00b0C. Then the next 20ppmv, taking it up to 40ppmv is 1.4\u00b0C. When it gets to 200ppmv then 20ppmv increments are reduced to 0.2\u00b0C and when it gets to 400ppmv then 20ppmv increments are reduced to 0.1\u00b0C. It seems to me that CO2 is having a real warming effect but it is miniscule and far too small to warrant drastic measures being taken worldwide to counteract it.\n\nhttps://preview.redd.it/yebd5viqxyd51.png?width=727&format=png&auto=webp&s=65d837ee6a5e630819a1401007239d854ed3405b",
        "created": "2020-07-30",
        "comment": "Linking to a picture on [blogspot.com](https://blogspot.com)? And on the \"average of studies\" conducted by seemingly a lot of contrarian/skeptic scientists (most probably a lot of these studies were not published in very reputable journals). The [IPCC](https://www.ipcc.ch/site/assets/uploads/2018/02/WG1AR5_TS_FINAL.pdf) tries to assess the whole body of science and they estimate an ECS of 1.5-4.5C  (TS.5.3 p. 81). And a very [recent piece](https://www.sciencemag.org/news/2020/07/after-40-years-researchers-finally-see-earths-climate-destiny-more-clearly), discussed recently here as well just narrowed this range as well to 2.6\u00b0C-3.9\u00b0C, and it assessed quite a lot of different lines of evidence. Increasingly the science has recently been saying that the low ECS estimates are unlikely. Also the high-end estimates, but the low-end even more so.\n\nYou don't really mention any sources so the basis for these assessments could basically be whatever. Even mentioning an exact number is not the standard way of reporting ECS numbers.\n\nOf course it's essentially possible to prove almost whichever point you want if you disregard or don't care for the major reports or most reputable journals and hand pick your sources. I can see that you post a lot on r/climateskeptics too.",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "49",
        "title": "Have you ever succeeded at convincing a denier that the climate change is real?",
        "score": "20",
        "id": "i03foq",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i03foq/have_you_ever_succeeded_at_convincing_a_denier/",
        "num_comments": "114",
        "body": "\n\n[View Poll](https://www.reddit.com/poll/i03foq)",
        "created": "2020-07-29",
        "comment": "My problem is convincing someone who certainly agrees that it is real, but simply does not care since it doesn\u2019t impact their life currently",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "50",
        "title": "Have you ever succeeded at convincing a denier that the climate change is real?",
        "score": "20",
        "id": "i03foq",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i03foq/have_you_ever_succeeded_at_convincing_a_denier/",
        "num_comments": "114",
        "body": "\n\n[View Poll](https://www.reddit.com/poll/i03foq)",
        "created": "2020-07-29",
        "comment": "Most deniers today don't argue against climate change being real. They argue against it being man-made and our need to counteract it.\n\nThe historical measurements from the past decades clearly show that the climate is changing. And they will be quick to point out, that this is normal and that the climate has always been changing. But they argue that it's all natural and nothing needs to be done about it.",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "51",
        "title": "Have you ever succeeded at convincing a denier that the climate change is real?",
        "score": "20",
        "id": "i03foq",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i03foq/have_you_ever_succeeded_at_convincing_a_denier/",
        "num_comments": "114",
        "body": "\n\n[View Poll](https://www.reddit.com/poll/i03foq)",
        "created": "2020-07-29",
        "comment": "Other: \"Hey dude if climate change is real then we won't get more weed in the future because of the co2 concentration in the air, man.\" \"Aw shit, we better get this global warming shit solved asap.\"",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "52",
        "title": "Have you ever succeeded at convincing a denier that the climate change is real?",
        "score": "20",
        "id": "i03foq",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i03foq/have_you_ever_succeeded_at_convincing_a_denier/",
        "num_comments": "114",
        "body": "\n\n[View Poll](https://www.reddit.com/poll/i03foq)",
        "created": "2020-07-29",
        "comment": "No. In my experience, any sort of evidence you provide is met with counter-evidence, even if said counter-evidence is fake. \n\nFor example, [in one case](https://np.reddit.com/r/climatechange/comments/hjop9s/how_can_we_manufacture_consent_for_climate_action/fwonuve/?context=100), I was sent links which purportedly show that there is a massive political+academic+business+media conspiracy that is faking climate change. That guy seems to believe that it must be a conspiracy if the scientific community agrees that climate change is real and is anthropogenic.\n\n**Edit**: I just realised now that the case I am referring to is on this very subreddit.",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "53",
        "title": "Have you ever succeeded at convincing a denier that the climate change is real?",
        "score": "20",
        "id": "i03foq",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i03foq/have_you_ever_succeeded_at_convincing_a_denier/",
        "num_comments": "114",
        "body": "\n\n[View Poll](https://www.reddit.com/poll/i03foq)",
        "created": "2020-07-29",
        "comment": "The are just too fixed minded",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "54",
        "title": "Have you ever succeeded at convincing a denier that the climate change is real?",
        "score": "20",
        "id": "i03foq",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i03foq/have_you_ever_succeeded_at_convincing_a_denier/",
        "num_comments": "114",
        "body": "\n\n[View Poll](https://www.reddit.com/poll/i03foq)",
        "created": "2020-07-29",
        "comment": "Convinced him it's real but natural, so there's nothing we can do but prepare and become a multiplanetary species ASAP.\nThat was his take away at least.\nAttempted to get him to admit it was man made but couldn't.",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "55",
        "title": "Have you ever succeeded at convincing a denier that the climate change is real?",
        "score": "20",
        "id": "i03foq",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i03foq/have_you_ever_succeeded_at_convincing_a_denier/",
        "num_comments": "114",
        "body": "\n\n[View Poll](https://www.reddit.com/poll/i03foq)",
        "created": "2020-07-29",
        "comment": "i convinced my parents that it was more urgent than they thought",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "56",
        "title": "Have you ever succeeded at convincing a denier that the climate change is real?",
        "score": "20",
        "id": "i03foq",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i03foq/have_you_ever_succeeded_at_convincing_a_denier/",
        "num_comments": "114",
        "body": "\n\n[View Poll](https://www.reddit.com/poll/i03foq)",
        "created": "2020-07-29",
        "comment": "Climate change is too complex a topic to lump everyone into a single category.  Denialism exists on a vast spectrum.  Eg some people deny we have 10 years left to take action. They say we have 12 or 20 or 50. \n\nU have to define what specifically is denied to get anywhere. \n\nI for one deny we are doomed in 12 years. I believe we have more like 50. And IPCC science supports that range. So who exactly am I denying if I say 50 and u say 12?",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "57",
        "title": "Have you ever succeeded at convincing a denier that the climate change is real?",
        "score": "20",
        "id": "i03foq",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i03foq/have_you_ever_succeeded_at_convincing_a_denier/",
        "num_comments": "114",
        "body": "\n\n[View Poll](https://www.reddit.com/poll/i03foq)",
        "created": "2020-07-29",
        "comment": "Most of the people I talk to bring up fake facts that say it\u2019s been going on for thousands of years and say it\u2019s not man made",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
    {
        "no": "58",
        "title": "Have you ever succeeded at convincing a denier that the climate change is real?",
        "score": "20",
        "id": "i03foq",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i03foq/have_you_ever_succeeded_at_convincing_a_denier/",
        "num_comments": "114",
        "body": "\n\n[View Poll](https://www.reddit.com/poll/i03foq)",
        "created": "2020-07-29",
        "comment": "\"Convincing a denier\". Let's just forget what we're talking about for a second and imagine it's a whole another topic.\n\nNow I don't know how your (OP) discussions have went of course - but I think that the rhetorics and words are fairly loaded here and if that's a starting point of a discussion I can't really imagine it going very well. I mean the rhetorics sound like something from the crusades.\n\nWhen someone's values are at stake in any case I wouldn't expect it to change over the course of a short discussion anyway. It's more like a seed taking place and growing with time. Well, peope are different of course but I'd guess it's fairly rare for anyone to change their minds on the spot over a serious issue.\n\nHaving been on reddit discussing these things I do think people change their minds over time. I certainly have. I think others have too. Mostly the changes of opinion are somewhat incremental though - it's hard to see anyone making great leaps instantly.\n\nCultural features, identities, ideologies and values play a huge role in peoples' opinions. Yet usually they aren't featured at all in the arguments which is in my opinion a big reason for the shouting at each other part. Things are just very different in different parts of the world, and in addition people were brought up differently in their collectives and families.",
        "is_same_stance": "T",
        "author_leaning": "N"
    },
    {
        "no": "59",
        "title": "Have you ever succeeded at convincing a denier that the climate change is real?",
        "score": "20",
        "id": "i03foq",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i03foq/have_you_ever_succeeded_at_convincing_a_denier/",
        "num_comments": "114",
        "body": "\n\n[View Poll](https://www.reddit.com/poll/i03foq)",
        "created": "2020-07-29",
        "comment": "I've never met a person who denies man made climate change. I think they only exist on the internet or the USA.",
        "is_same_stance": "T",
        "author_leaning": "N"
    },
    {
        "no": "60",
        "title": "Have you ever succeeded at convincing a denier that the climate change is real?",
        "score": "20",
        "id": "i03foq",
        "subreddit": "climatechange",
        "url": "https://www.reddit.com/r/climatechange/comments/i03foq/have_you_ever_succeeded_at_convincing_a_denier/",
        "num_comments": "114",
        "body": "\n\n[View Poll](https://www.reddit.com/poll/i03foq)",
        "created": "2020-07-29",
        "comment": "I fired my financial advisor after he told me he believed it is caused by solar flares. And a bunch of other crap straight out of the Fox News  playlist and horrible stuff about Greta Thunberg",
        "is_same_stance": "F",
        "author_leaning": "N"
    },
]